version: '3'

services:
  sut:
    build: .
    command: npm test
    environment:
      - DB_URL=mongodb://mongodb/notetaking
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
